// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/moneothingrawdatas/timerange": {
            "post": {
                "description": "get moneothing by value",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "get moneothing",
                "parameters": [
                    {
                        "description": "Add account",
                        "name": "timestamprangesearchdto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.timestamprangesearchdto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.moneothingwithvalue"
                            }
                        }
                    }
                }
            }
        },
        "/moneothingrawdatas/timestamp": {
            "post": {
                "description": "get moneothing by value",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "get moneothing",
                "parameters": [
                    {
                        "description": "Add account",
                        "name": "timestampsearchdto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.timestampsearchdto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.moneothingwithvalue"
                            }
                        }
                    }
                }
            }
        },
        "/moneothingrawdatas/value": {
            "post": {
                "description": "get moneothing by value",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "get moneothing",
                "parameters": [
                    {
                        "description": "Add account",
                        "name": "valuesearchdto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.valuesearchdto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.moneothingwithvalue"
                            }
                        }
                    }
                }
            }
        },
        "/rawdatas": {
            "post": {
                "description": "get rawdatas by value",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Show rawdatas",
                "parameters": [
                    {
                        "description": "Add account",
                        "name": "valuesearchdto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.valuesearchdto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.rawdataviewmodel"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.moneothingwithvalue": {
            "type": "object",
            "properties": {
                "displayname": {
                    "type": "string"
                },
                "thingid": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "uniqueidentifier": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "main.rawdataviewmodel": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "main.timestamprangesearchdto": {
            "type": "object",
            "properties": {
                "from": {
                    "type": "string"
                },
                "pagenumber": {
                    "type": "integer"
                },
                "pagesize": {
                    "type": "integer"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "main.timestampsearchdto": {
            "type": "object",
            "properties": {
                "lower": {
                    "type": "boolean"
                },
                "pagenumber": {
                    "type": "integer"
                },
                "pagesize": {
                    "type": "integer"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "main.valuesearchdto": {
            "type": "object",
            "properties": {
                "pagenumber": {
                    "type": "integer"
                },
                "pagesize": {
                    "type": "integer"
                },
                "value": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
