definitions:
  main.moneothingwithvalue:
    properties:
      displayname:
        type: string
      thingid:
        type: string
      timestamp:
        type: string
      uniqueidentifier:
        type: string
      value:
        type: string
    type: object
  main.rawdataviewmodel:
    properties:
      id:
        type: integer
      value:
        type: string
    type: object
  main.timestamprangesearchdto:
    properties:
      from:
        type: string
      pagenumber:
        type: integer
      pagesize:
        type: integer
      to:
        type: string
    type: object
  main.timestampsearchdto:
    properties:
      lower:
        type: boolean
      pagenumber:
        type: integer
      pagesize:
        type: integer
      time:
        type: string
    type: object
  main.valuesearchdto:
    properties:
      pagenumber:
        type: integer
      pagesize:
        type: integer
      value:
        type: string
    type: object
info:
  contact: {}
paths:
  /moneothingrawdatas/timerange:
    post:
      consumes:
      - application/json
      description: get moneothing by value
      parameters:
      - description: Add account
        in: body
        name: timestamprangesearchdto
        required: true
        schema:
          $ref: '#/definitions/main.timestamprangesearchdto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.moneothingwithvalue'
            type: array
      summary: get moneothing
      tags:
      - accounts
  /moneothingrawdatas/timestamp:
    post:
      consumes:
      - application/json
      description: get moneothing by value
      parameters:
      - description: Add account
        in: body
        name: timestampsearchdto
        required: true
        schema:
          $ref: '#/definitions/main.timestampsearchdto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.moneothingwithvalue'
            type: array
      summary: get moneothing
      tags:
      - accounts
  /moneothingrawdatas/value:
    post:
      consumes:
      - application/json
      description: get moneothing by value
      parameters:
      - description: Add account
        in: body
        name: valuesearchdto
        required: true
        schema:
          $ref: '#/definitions/main.valuesearchdto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.moneothingwithvalue'
            type: array
      summary: get moneothing
      tags:
      - accounts
  /rawdatas:
    post:
      consumes:
      - application/json
      description: get rawdatas by value
      parameters:
      - description: Add account
        in: body
        name: valuesearchdto
        required: true
        schema:
          $ref: '#/definitions/main.valuesearchdto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.rawdataviewmodel'
            type: array
      summary: Show rawdatas
      tags:
      - accounts
swagger: "2.0"
