// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/moneothingrawdatas/value": {
            "post": {
                "description": "get moneothing by value",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "moneothingrawdatas"
                ],
                "summary": "get moneothing",
                "parameters": [
                    {
                        "description": "get moneothing by value",
                        "name": "valuesearchdto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.valuesearchdto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.moneothingwithvalue"
                            }
                        }
                    }
                }
            }
        },
        "/moneothings": {
            "post": {
                "description": "get moneothing",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "moneothings"
                ],
                "summary": "get moneothing",
                "parameters": [
                    {
                        "description": "get a moneothing",
                        "name": "moneothingsearchdto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.moneothingsearchdto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.moneothing"
                        }
                    }
                }
            }
        },
        "/moneothings/all": {
            "get": {
                "description": "get all moneothings",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "moneothings"
                ],
                "summary": "Get all moneothings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.moneothing"
                            }
                        }
                    }
                }
            }
        },
        "/moneothingwithrawdatas/timerange": {
            "post": {
                "description": "get values for moneothing",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "moneothingwitrawdatas"
                ],
                "summary": "get values for moneothing in given timerange",
                "parameters": [
                    {
                        "description": "Rawdatas for timerange",
                        "name": "moneothingrawdatatimerangedto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.moneothingrawdatatimerangedto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.moneothingwithvaluesviewmodel"
                        }
                    }
                }
            }
        },
        "/moneothingwithrawdatas/timestamp": {
            "post": {
                "description": "get values for moneothing",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "moneothingwitrawdatas"
                ],
                "summary": "get values for moneothing at timestamp",
                "parameters": [
                    {
                        "description": "Rawdata next to timerange",
                        "name": "moneothingrawdatatimestampdto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.moneothingrawdatatimestampdto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.moneothingwithvaluesviewmodel"
                        }
                    }
                }
            }
        },
        "/rawdatas": {
            "post": {
                "description": "get rawdatas by value",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rawdatas"
                ],
                "summary": "Show rawdatas",
                "parameters": [
                    {
                        "description": "Get rawdatas",
                        "name": "valuesearchdto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.valuesearchdto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.rawdataviewmodel"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.moneothing": {
            "type": "object",
            "properties": {
                "Data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.moneothingrawdata"
                    }
                },
                "displayname": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "thingid": {
                    "type": "string"
                },
                "uniqueidentifier": {
                    "type": "string"
                }
            }
        },
        "main.moneothingrawdata": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "moneothing": {
                    "$ref": "#/definitions/main.moneothing"
                },
                "rawdata": {
                    "$ref": "#/definitions/main.rawdata"
                },
                "rawdataid": {
                    "type": "integer"
                },
                "thingid": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "main.moneothingrawdatatimerangedto": {
            "type": "object",
            "properties": {
                "fromtime": {
                    "type": "string"
                },
                "pagenumber": {
                    "type": "integer"
                },
                "pagesize": {
                    "type": "integer"
                },
                "thingid": {
                    "type": "string"
                },
                "totime": {
                    "type": "string"
                },
                "uniqueidentifier": {
                    "type": "string"
                }
            }
        },
        "main.moneothingrawdatatimestampdto": {
            "type": "object",
            "properties": {
                "thingid": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "uniqueidentifier": {
                    "type": "string"
                }
            }
        },
        "main.moneothingsearchdto": {
            "type": "object",
            "properties": {
                "pagenumber": {
                    "type": "integer"
                },
                "pagesize": {
                    "type": "integer"
                },
                "thingid": {
                    "type": "string"
                },
                "uniqueidentifier": {
                    "type": "string"
                }
            }
        },
        "main.moneothingwithvalue": {
            "type": "object",
            "properties": {
                "displayname": {
                    "type": "string"
                },
                "thingid": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "uniqueidentifier": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "main.moneothingwithvaluesviewmodel": {
            "type": "object",
            "properties": {
                "displayname": {
                    "type": "string"
                },
                "rawdatas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.valuewithtimestampviewmodel"
                    }
                },
                "thingid": {
                    "type": "string"
                },
                "uniqueidentifier": {
                    "type": "string"
                }
            }
        },
        "main.rawdata": {
            "type": "object",
            "properties": {
                "Data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.moneothingrawdata"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "main.rawdataviewmodel": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "main.valuesearchdto": {
            "type": "object",
            "properties": {
                "pagenumber": {
                    "type": "integer"
                },
                "pagesize": {
                    "type": "integer"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "main.valuewithtimestampviewmodel": {
            "type": "object",
            "properties": {
                "timestamp": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	
	
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
