definitions:
  main.moneothing:
    properties:
      Data:
        items:
          $ref: '#/definitions/main.moneothingrawdata'
        type: array
      displayname:
        type: string
      id:
        type: integer
      thingid:
        type: string
      uniqueidentifier:
        type: string
    type: object
  main.moneothingrawdata:
    properties:
      id:
        type: integer
      moneothing:
        $ref: '#/definitions/main.moneothing'
      rawdata:
        $ref: '#/definitions/main.rawdata'
      rawdataid:
        type: integer
      thingid:
        type: integer
      timestamp:
        type: integer
    type: object
  main.moneothingrawdatatimerangedto:
    properties:
      fromtime:
        type: string
      pagenumber:
        type: integer
      pagesize:
        type: integer
      thingid:
        type: string
      totime:
        type: string
      uniqueidentifier:
        type: string
    type: object
  main.moneothingrawdatatimestampdto:
    properties:
      thingid:
        type: string
      time:
        type: string
      uniqueidentifier:
        type: string
    type: object
  main.moneothingsearchdto:
    properties:
      pagenumber:
        type: integer
      pagesize:
        type: integer
      thingid:
        type: string
      uniqueidentifier:
        type: string
    type: object
  main.moneothingwithvalue:
    properties:
      displayname:
        type: string
      thingid:
        type: string
      timestamp:
        type: string
      uniqueidentifier:
        type: string
      value:
        type: string
    type: object
  main.rawdata:
    properties:
      Data:
        items:
          $ref: '#/definitions/main.moneothingrawdata'
        type: array
      id:
        type: integer
      value:
        type: string
    type: object
  main.rawdataviewmodel:
    properties:
      id:
        type: integer
      value:
        type: string
    type: object
  main.valuesearchdto:
    properties:
      pagenumber:
        type: integer
      pagesize:
        type: integer
      value:
        type: string
    type: object
info:
  contact: {}
paths:
  /moneothingrawdatas/timerange:
    post:
      consumes:
      - application/json
      description: get moneothing by value
      parameters:
      - description: get moneothing with rawdata by timerange
        in: body
        name: moneothingrawdatatimerangedto
        required: true
        schema:
          $ref: '#/definitions/main.moneothingrawdatatimerangedto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.moneothingwithvalue'
            type: array
      summary: get moneothing with rawdata
      tags:
      - moneothingrawdatas
  /moneothingrawdatas/timestamp:
    post:
      consumes:
      - application/json
      description: get moneothing by timestamp
      parameters:
      - description: get moneothing by timestamp
        in: body
        name: moneothingrawdatatimestampdto
        required: true
        schema:
          $ref: '#/definitions/main.moneothingrawdatatimestampdto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.moneothingwithvalue'
            type: array
      summary: get moneothing
      tags:
      - moneothingrawdatas
  /moneothings:
    post:
      consumes:
      - application/json
      description: get moneothing
      parameters:
      - description: get a moneothing
        in: body
        name: moneothingsearchdto
        required: true
        schema:
          $ref: '#/definitions/main.moneothingsearchdto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.moneothing'
      summary: get moneothing
      tags:
      - moneothings
  /moneothings/all:
    get:
      consumes:
      - application/json
      description: get all moneothings
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.moneothing'
            type: array
      summary: Get all moneothings
      tags:
      - moneothings
  /rawdatas:
    post:
      consumes:
      - application/json
      description: get rawdatas by value
      parameters:
      - description: Get rawdatas
        in: body
        name: valuesearchdto
        required: true
        schema:
          $ref: '#/definitions/main.valuesearchdto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.rawdataviewmodel'
            type: array
      summary: Show rawdatas
      tags:
      - rawdatas
swagger: "2.0"
