# Directory in which the generated static code is to be kept.
output = "models" 

# Each time new code is generated, completely wipe out the old one.
wipe = true

# The `go` package name used in the generated code.
pkgname = "dbmodels"

# Adds global variant of the generated functions, more on this later.
add-global-variants = true

# Generates code for enum types as well.
add-enum-types = true

# This is the postgres config, which should be self explanatory.
[psql]
dbname = "processdata"
host = "192.168.66.11"
port = 5439
user = "richie"
pass = "0NolonopA0"
sslmode = "disable"